name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0-3'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

env:
  MY_REPO_WORKFLOW_S: ${{secrets.MY_REPO_SECRET}}
  MY_REPO_WORKFLOW_V: ${{vars.MY_REPO_VAR}}
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0
        with: 
          repository: geovanams/demo1

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "🧪 Testing..."
          echo "MY_REPO_WORKFLOW_S = $MY_REPO_WORKFLOW_S"
          echo "MY_REPO_WORKFLOW_V = $MY_REPO_WORKFLOW_V"

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    env:
      MY_PROD_SECRET: ${{secrets.MY_PROD_SECRET}}
      MY_PROD_VAR: ${{vars.MY_PROD_VAR}}
    steps:
      - run: |
          echo "🚀 Step 1..."
          echo "MY_MY_PROD_SECRET: $MY_PROD_SECRET"
          echo "MY_PROD_VAR: $MY_PROD_VAR"
      - run: |
          echo "🚀 Step 2..."
          sleep 10
